language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode

matrix:
  include:
    - rvm: "jruby-19mode"
      jdk: "openjdk7"
    - rvm: "jruby-19mode"
      jdk: "oraclejdk7"
    - rvm: "jruby-19mode"
      jdk: "openjdk6"

